#:schema node_modules/wrangler/config-schema.json
name = "rag-application"
main = "src/index.js"
compatibility_date = "2024-12-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "rag-application-custom"
database_id = "445ea402-dcf4-49f3-9831-d9745ccf6339"

[ai]
binding = "AI"

